/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // 从 docs 根目录自动生成
    },
  ],
};

module.exports = sidebars;
